kumuluzee:
  name: uporabniki-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CustomerDS
      connection-url: jdbc:postgresql://localhost:5432/customer
      username: dbuser
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CustomerDS
    metrics:
      web-instrumentation:
        - name: uporabniki-endpoint
          url-pattern: /v1/uporabniki/*
  rest-client:
    registrations:
      - class: customer-api
        url: http://localhost:8082/v1
        read-timeout: 5000
    ttl: 20
    ping-interval: 15
  config:
    consul:
      agent: http://consul:8500
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                                  <Configuration name="uporabniki">
                                      <Appenders>
                                          <Console name="console" target="SYSTEM_OUT">
                                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                          </Console>
                                          <Socket name="logstash" host="e36c8ff6-8abf-4557-8fb5-1b031a4459db-ls.logit.io"
                                          port="24269" protocol="udp">
                                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                          </Socket>
                                      </Appenders>
                                      <Loggers>
                                          <!-- Default logger -->
                                          <Root level="all">
                                              <AppenderRef ref="console" level="info" />
                                              <AppenderRef ref="logstash" level="trace" />
                                          </Root>
                                      </Loggers>
                                  </Configuration>'
rest-properties:
  maintenance-mode: false

