kumuluzee:
  name: uporabniki-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CustomerDS
      connection-url: jdbc:postgresql://localhost:5432/customer
      username: dbuser
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CustomerDS
    metrics:
      web-instrumentation:
        - name: uporabniki-endpoint
          url-pattern: /v1/uporabniki/*
  rest-client:
    registrations:
      - class: customer-api
        url: http://localhost:8082/v1
        read-timeout: 5000
  discovery:
    cluster: 1
    consul:
      agent: http://localhost:8500
    ttl: 20
    ping-interval: 15
rest-properties:
  maintenance-mode: false

